### PR TITLE
Improved German translation

### PR DESCRIPTION
**Pull request by MimzyFang**
Did some small changes to the German translations it has been proofread by a friend of mine

### CODE REVIEW

**Comment by MimzyFang** [comment]
Closed because it's a mess gonna fix it later

**Review by Sollace — APPROVED** [review]

**Comment by Sollace** [comment]
Looks good!

One thing, not really important, but I wonder whether we should translate the name too? Like change "Mine Little Pony" to "Mein Kleines Pony" (translated via google translate)?

**Comment by MimzyFang** [comment]
I refuse to translate branding

**Comment by MimzyFang** [comment]
Also My Little Pony: Friendship is Magic was translated to My Little Pony – Freundschaft ist Magie 
so keeping the name English would be in line with the show

**Comment by Sollace** [comment]
Merged, thanks!

**Pull request merged**
