### PR TITLE
Giants are now ponies

### PR DESCRIPTION
**Pull request by Sollace**
This just adds the long forgotten model for giant zombies. It always bothered me that this mod didn't work on giants even though they're supposed to have the same model. :T

### CODE REVIEW

**Comment by Brian151** [comment]
why not? XD
hope this gets merged!

**Comment by killjoy1221** [comment]
It would be nice to have giants as a Sphinx, but I guess this is good enough for the interim.

I hate to do this, but can you try to keep to the existing style? I prefer to use spaces. It really shouldn't be a problem since your IDE does this for you. Also, try not to commit things that aren't relevant to the PR.

And just FYI, I'm not going to merge the warnings commit.

**Comment by Brian151** [comment]
@killjoy1221 

as a suggestion, why not both?
Someone could make sphinx skins, too, right?

**Comment by Sollace** [comment]
@killjoy1221 
Um, sure... I can _try_. Don't really know how to get Eclipse not to use tabs. Also how would you create a PR out of just one commit? It only ever seems to take the entire branch, to now to make other PRs I have to go back and rebase all their branches over this one again.

**Comment by killjoy1221** [comment]
Don't worry about individual commits. I can exclude them manually. Just fix
the spaces and formatting.

**Comment by Sollace** [comment]
Alright. I will fix my spaces in future PRs.

I think there' only the one on BigPonies, and two branches I can rebase once that one's gone through.

**Pull request closed without merging**
