### PR TITLE
It's a bird! it's a plane!

### PR DESCRIPTION
**Pull request by Sollace**
As requested, flying ponies will now wear elytra as capes.

This just makes it so that pegasi, alicorns, and other winged creatures will use their wings to fly rather than their elytras. The elytra itself just acts like a decorative cape.

(if you merge this, let me know and I will rebase the rest)

### CODE REVIEW

**Comment by killjoy1221** [comment]
I'm not really a fan of the concept. The elytra is a tool. Why would pegasi use it to fly when they can just flap their wings? The answer is because they don't feel like it. 

Elytra flying isn't the same as creative flying, so we shouldn't treat the animation the same.

**Comment by Sollace** [comment]
@killjoy1221 The thing is, in survival pegasi are unable to fly unless they have the elytra on. But it looks weird to be flying with the elytra if they have wings.

**Comment by ZeldaLinkAaron** [comment]
Maybe make them glide with the Elytra instead of just flapping their wings?

**Comment by killjoy1221** [comment]
We may not be able to fly in survival in vanilla, but some mods add support for that. I don't want to mess with the mechanics too much.

**Pull request closed without merging**
