### PR TITLE
Fixes for wing rendering

### PR DESCRIPTION
**Pull request by Venaf**
Changed PonySkinModifier to remove the baked-in wing mirroring when it converts old skins to the advanced format, and instead perform mirroring in PegasusWings.  Tested with standard definition and HD skins, displays consistently for both old skins and advanced skins.  

The old to new skin converter will probably need updated if this pull is accepted, since it includes the baked-in mirroring when it converts the wing texture.

Also changed vertical alignment on the wings in relation to the body slightly; the right extended wing was about a pixel higher than the left one.  Moved both of them half a unit towards the midpoint, now they flap from the center of the wing/plume instead of the top/bottom edge.

### CODE REVIEW

**Comment by killjoy1221** [comment]
Don't worry about travis. I haven't added a `.travis.yml` yet.

Can you explain why this is needed instead of just changing it in your skin texture? The extended wings are essentially thin legs. That's why the parts for it in the skin converter are the way they are. Neither wings would need to be mirrored. There's no need to since the texture can be whatever.

Also, what's up with the wing positioning? Are they a little off-center?

**Comment by Venaf** [comment]
Looks like I made a mistake.  I've been looking at a lot of HD skins which must've been improperly made, because they wouldn't match up left and right, and I couldn't find a good template anywhere that actually displays where each part of the wing area maps to the model.  So the texture change isn't necessary, although it could make for advanced skins to be a little easier to figure out at a glance, since only parts of the wing are reversed in the texture and not the whole block.

As for the wing positioning, if you look at the pony from behind, the right wing is higher than the other when flying or sneaking, and the rotation point is different for each side for the flapping; it's at the top of the wing rectangle on one side, and at the bottom for the other side.

**Comment by Venaf** [comment]
Here's some picture examples of the wing height issue.

In this one you can see fairly clearly how they don't line up.  It's only really obvious from directly behind, and I would never have noticed if I wasn't looking so close at the wings all night.


And here you can see the difference in rotation points causing the right wing to clip into the body more, while the left is almost disconnected.

**Comment by killjoy1221** [comment]
I'll accept the wing positions, but I'll need more reason and details for
the texture mirroring.

**Comment by Venaf** [comment]
Other than simplifying the wing layout on the advanced texture file, there's no compelling reason to change.  Again, I think I perceived an issue because I couldn't find good documentation or templates of the wing specifics, as only parts of the texture get flipped while the right edge of the wing texture block stays the same.  I'm not that familiar with Git; should I close this and submit a separate pull request with only the positioning changes on the wings?  Thanks for your patience in reviewing this.

**Comment by killjoy1221** [comment]
You can if you want. Doesn't matter to me.

**Comment by killjoy1221** [comment]
Also, if you pull from `master` right now, jenkins will work.

**Pull request closed without merging**
