### PR TITLE
Instructions For Users

### PR DESCRIPTION
**Pull request by Andy-K-Sparklight**
I wrote a ~clearer~ guide to help users to install fabric. I already tested it on both my Windows 10 and Ubuntu 18.04.  
(I went through a lot of difficulties during installation as well)

### CODE REVIEW

**Comment by killjoy1221** [comment]
If l it would be useful if you also did this on https://github.com/minelittlepony/minelittlepony.github.io

**Comment by Andy-K-Sparklight** [comment]
It’s already 23:00 now here (GMT+8) I’ll write the HTML page tomorrow, that will be... 16:00PM (GMT-7)

**Comment by Sollace** [comment]
I will not "direct" links may not be such a good idea, in the event Modmuss releases a new version. Ideally this shouldn't be something that I have to continually check and update.

**Comment by Andy-K-Sparklight** [comment]
So just RM it. Only the Fabric ML has a direct link. ~Thought maybe it would be useful.~ But yeah, let the players to click the download link on that page so updates of this guide isn’t necessary.
Sorry I’m not able to change code here. I don’t have Git on my iPad, you may want to fix this, or if not, I’ll deal with it tomorrow together with this page on GitHub Pages as required.

**Comment by keupoz** [comment]
> It’s already 23:00 now here (GMT+8) I’ll write the HTML page tomorrow, that will be... 16:00PM (GMT-7)

I don't think it will fit the site design. I already updated install guides to be simple. Yours is too complex. It could have a different page but currently there's a new site source code which is WIP

**Comment by PCelestia** [comment]
maybe include it as a detailed guide since there might be someone that wants it

**Comment by Andy-K-Sparklight** [comment]
> I don't think it will fit the site design. I already updated install guides to be simple. Yours is too complex. It could have a different page but currently there's a new site source code which is WIP  
Oh, okay, I just wanted to give a detailed one. If a simple one fit the site design that will be better.

**Comment by Andy-K-Sparklight** [comment]
Seems it isn’t needed now, this PR is closed, for no future requests or work needed.

**Pull request closed without merging**
